### ISSUE TITLE
Calculate marketprice for specific amount

### ISSUE THREAD

**Issue by Krachwumm** [hardlydifficult/Crypnostic#13]
Calculate the marketprice for x amount of coins by adding the best bids/asks from the orderbook together while considering their amounts.

**Comment by hardlydifficult** [comment]
In addition to checking depth for x amount of coins, could offer:
 - x amount of BTC or ETH
 - something about profit depth (maybe up to 2 ETH if above the buy price in this other book)

**Comment by hardlydifficult** [comment]
From wumm: The algorithm: https://pastebin.com/U8TuKDkJ

**Comment by hardlydifficult** [comment]
WIP. This and the "best" methods are tools. I think we should extract into a separate class.

**Comment by hardlydifficult** [comment]
Done.  Lemme know if there is something we missed.
