### ISSUE TITLE
Exchange EtherDelta: Switch to ForkDelta API

### ISSUE THREAD

**Issue by HardlyDifficult** [HardlyDifficult/Crypnostic#22]

**Comment by hardlydifficult** [comment]
I could use help on this one...

**Comment by hardlydifficult** [comment]
https://github.com/forkdelta/backend-replacement/issues/34

Thanks Nizero

**Comment by hardlydifficult** [comment]
ForkDelta API Reference: https://www.reddit.com/r/ForkDelta/comments/7pen41/api_for_forkdelta/
