### ISSUE TITLE
New Name

### ISSUE THREAD

**Issue by hardlydifficult** [hardlydifficult/Crypnostic#36]
Suggestions?  Leave a comment below.

**Comment by hardlydifficult** [comment]
This is an exchange-agnostic C# API.  Currently we are working on downloading information from the public API and aggregating the data from various exchanges.  We will then add support for the private APIs, e.g. checking balances or actually making a trade.  And finally we may add some tools - e.g. help discover arbitrage opportunities or consider fees and order depth before recommending a trade.

**Comment by impowski** [comment]
CryptOctopus, CryptoPod, HeptaConnect, HeptaPort, SquidPod, SquidPort, SquidConnect.

**Comment by okdoomfist** [comment]
cryptounite

**Comment by jlapaix** [comment]
cryptonononoo

**Comment by thepinkfreudian** [comment]
Blockchange (or Blockchainge for extra pun power)

**Comment by impmja** [comment]
Coinly
CoinLink
CoinConnect
Coinytrage
CoinEx
Exchangly
Moonfahrer
ExoCoin
ExoCrypt

**Comment by hardlydifficult** [comment]
Crypnostic.
