### ISSUE TITLE
Getting a NullReferenceException in Exchange.cs

### ISSUE THREAD

**Issue by Krachwumm** [hardlydifficult/Crypnostic#43]
Getting a NullReferenceException at Exchange.cs line 188: "await GetAllTradingPairsWrapper();"
I've tried not using the exchange it complains about, but it happens for every one of them.

Call Stack:
> [External Code]
> CrypConnect.dll!CrypConnect.Exchange.Timer_Elapsed(object sender, System.Timers.ElapsedEventArgs e) Line 188
> [Resuming Async Method]
> [External Code]
> CrypConnect.dll!CrypConnect.Exchange.GetAllTradingPairsWrapper(bool preventRetryOnFail) Line 181
> [Resuming Async Method]
> [External Code]

**Comment by hardlydifficult** [comment]
Thanks, my run didn't do well last night either.  We'll work on logging and error handling/retry today.

**Comment by hardlydifficult** [comment]
Does this still repro? Anything in the logs?

**Comment by Krachwumm** [comment]
No, works fine now. Thanks!

**Comment by hardlydifficult** [comment]
Hmm. I think this may be the coin exists in dictionary issue. Need to read up as this may have other implications..

**Comment by hardlydifficult** [comment]
I'll close this for now. Thanks!
