### ISSUE TITLE
Error in Exchange.cs.AddTicker()

### ISSUE THREAD

**Issue by Krachwumm** [hardlydifficult/Crypnostic#44]
Idex produces an error because it has two coins named Gazecoin.
GZE and GZENEW

While trying to add Gazecoin to coinToTickerLower, the key already exists, which breaks the code.

**Comment by hardlydifficult** [comment]
Thanks, will take a look today.

**Comment by hardlydifficult** [comment]
Getting closer, I have an approach in mind... but the code is WIP so not going to check in until after more testing - ETA tomorrow.
