### ISSUE TITLE
Regression: CoinExtensions.cs 

### ISSUE THREAD

**Issue by mgalpy** [hardlydifficult/Crypnostic#58]
Minor regression inside CoinExtensions.cs , line 20, causes the project not to compile.

Original: ExchangeName[] onlyOnTheseExchanges = null)
New:      ExchangeName[] onlyOnTheseExchanges)

Seems that it should be reverted back to the original unless you had something else in mind.

**Comment by hardlydifficult** [comment]
I changed it again since then.  It's now IEnumerable<ExchangeName> instead of an array (allowing to pass an array or a list, but we lose the params support).

The examples should be compiling now.  Let me know if there's more issues.

thanks,
nick.
